### ISSUE TITLE
This needs to be changed to private

### ISSUE THREAD

**Issue by johnlev** [CouleeApps/MissionImpossible#1]

**Comment by CouleeApps** [comment]
I forgot this even existed still. Any reason to private it?

**Comment by johnlev** [comment]
There are files with real data about students and their march intensive choices. Probably nothing, but for the sake of good practices and privacy we should keep that data hidden

**Comment by CouleeApps** [comment]
Fair enough, but I'm not going to use one of my few private repos on it. Do you want control so you can do whatever, or should I just torch the online repo?

**Comment by johnlev** [comment]
You can torch it. I'm gonna archive it on a hard drive in case they ever want it.

**Comment by CouleeApps** [comment]
Alright.
